name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ./
    - name: Check sort with disorder
      run: sort -c test/test.txt || true
    - name: Check sort with disorder in an unusually named file
      run: sort -c test/test:2.txt || true
